### ISSUE TITLE
Doesn't run with input.txt

### ISSUE THREAD

**Issue by nplotnik** [tsarapkin/informatics3term#2]
[nick@arch_host informatics3term]$ ./a.out 
/home/nick/students_works/informatics3term
[nick@arch_host informatics3term]$ cat input.txt 
1 ls
2 pwd
3 ls -la

**Comment by tsarapkin** [comment]
надо 1 строкой подавать количество команд

2015-12-16 0:24 GMT+03:00 koljan818 notifications@github.com:

**Comment by tsarapkin** [comment]
например
2
1 ls
5 ./a.out ls

2015-12-16 0:32 GMT+03:00 Алексей Царапкин dangerous1cake@gmail.com:

**Comment by nplotnik** [comment]
Нет, такого не было в задании. 
Количество команд неизвестно заранее

**Comment by tsarapkin** [comment]
да какая разница, так удобнее в разы

16 декабря 2015 г., 0:41 пользователь koljan818 notifications@github.com
написал:

**Comment by tsarapkin** [comment]
все,теперь без количества комманд можно, пробуйте

16 декабря 2015 г., 0:47 пользователь Алексей Царапкин <
dangerous1cake@gmail.com> написал:

**Comment by nplotnik** [comment]
[nick@arch_host informatics3term]$ git pull
Already up-to-date.
[nick@arch_host informatics3term]$ gcc useless.c 
[nick@arch_host informatics3term]$ ls
a.out  input.txt  ls2var.c  ls.c  useless.c
[nick@arch_host informatics3term]$ ./a.out 
/home/nick/students_works/informatics3term
[nick@arch_host informatics3term]$ cat input.txt 
1 ls
2 pwd
3 ls -la

**Comment by tsarapkin** [comment]
я случайно создал ветку с изменением, а основа не изменилась, вы эту основу
и использовали
Теперь основа проапгрейжена, пробуйте

2015-12-16 1:49 GMT+03:00 koljan818 notifications@github.com:
